# Generated by Django 4.2.20 on 2025-12-10 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            code=lambda apps, schema_editor: apps.get_model('listings', 'Category').objects.bulk_create(
                [
                    apps.get_model('listings', 'Category')(name='Cars', slug='cars', description='Used cars, SUVs, trucks.'),
                    apps.get_model('listings', 'Category')(name='Phones', slug='phones', description='Smartphones and accessories.'),
                    apps.get_model('listings', 'Category')(name='Electronics', slug='electronics', description='Laptops, tablets, TVs.'),
                    apps.get_model('listings', 'Category')(name='Home & Furniture', slug='home-furniture', description='Appliances, decor, furniture.'),
                ]
            ),
            reverse_code=migrations.RunPython.noop,
        ),
    ]
